### ISSUE TITLE
November 15 Homework Discussion

### ISSUE THREAD

**Issue by derrxb** [KED-2020/mind-map#14]
Hey guys. Here’s a breakdown of the task we would need to complete to get this homework done. I think we can separate it by the three main tasks.

### Project Refactor

The project needs to be refactored to be in the DDD setup. We also need to rename the domain entities to match the language used in our project.
* Resource => Document
* ...etc, I'm not super sure how much we'd want to rename.

### GitHub Data Source

The main change to this would be to provide a more meaningful repository functionality that other parts of the system can then call. For example, currently, if you search for a term, the first result is returned or no result is returned. However, this isn't very useful as we would like more than one results.`

### Inbox

The inbox should be able to do the following:
* Display a list of suggestions to a user
* Allow a user to select or discard a suggestion

### Favorites

Favourites should load and display the documents the user has saved. 

#### Thoughts

I think the main things we should try to get done should be the project refactor, GitHub data source, and the inbox. If we have time, we should work on the favourites option.

**Comment by derrxb** [comment]
## Inbox

Inbox is the central location where the suggestions for subscribed topics are given to a user. Once in the inbox, a user should be able to save or discard a suggestion given to them.

Inboxes themselves are unique by URL (i.e. this would be similar to code sandboxes: https://codesandbox.io/s/sad-almeida-m0nec). Suggestions are grouped by the inbox they are given to. So this means that a suggestion can belong to many inboxes and an inbox can have many suggestions.

### Nouns

* **Inbox**
* **Suggestions**
* **Topics**

#### Comments

I think inbox, suggestions, and topics all need to be saved in the database. So I'll need to add migrations to get this to work. I'll add two migrations (1 for inbox and 1 for the suggestion) for now. The last one to add will be topics. I think this is because we need to figure out is the best place for the topic to be added.

Inbox
- id
- name
- description
- unique_url_id

Suggestion
- id
- title
- description
- url

### Verbs

* **Suggest**
* **Save Suggestion**
* **Discard Suggestion**

#### Workflow

1. User creates a new inbox
2. They are directed to their inbox. They should be able to edit their inbox's name, description, etc. (We can probably leave implementing `editing` for later.
3. The user receives suggestions
4. The user saves or discards suggestions
5. The suggestion is removed from their inbox.

**Comment by Kyeg** [comment]
## New storyboard:

![image](https://user-images.githubusercontent.com/12498220/99181147-95024200-2767-11eb-9a12-b02a032aec91.png)
![image](https://user-images.githubusercontent.com/12498220/99179882-7d718c00-275c-11eb-89c9-122c23b0bd1f.png)
